# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/tempconv.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/tempconv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/tempconv.proto\x12\x08tempconv\"\x1c\n\x0bTempRequest\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1d\n\x0cTempResponse\x12\r\n\x05value\x18\x01 \x01(\x01\x32\x9d\x01\n\x0fTempConvService\x12\x44\n\x13\x43\x65lsiusToFahrenheit\x12\x15.tempconv.TempRequest\x1a\x16.tempconv.TempResponse\x12\x44\n\x13\x46\x61hrenheitToCelsius\x12\x15.tempconv.TempRequest\x1a\x16.tempconv.TempResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.tempconv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPREQUEST']._serialized_start=35
  _globals['_TEMPREQUEST']._serialized_end=63
  _globals['_TEMPRESPONSE']._serialized_start=65
  _globals['_TEMPRESPONSE']._serialized_end=94
  _globals['_TEMPCONVSERVICE']._serialized_start=97
  _globals['_TEMPCONVSERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
