# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tempconv_pb2 as protos_dot_tempconv__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/tempconv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TempConvServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CelsiusToFahrenheit = channel.unary_unary(
                '/tempconv.TempConvService/CelsiusToFahrenheit',
                request_serializer=protos_dot_tempconv__pb2.TempRequest.SerializeToString,
                response_deserializer=protos_dot_tempconv__pb2.TempResponse.FromString,
                _registered_method=True)
        self.FahrenheitToCelsius = channel.unary_unary(
                '/tempconv.TempConvService/FahrenheitToCelsius',
                request_serializer=protos_dot_tempconv__pb2.TempRequest.SerializeToString,
                response_deserializer=protos_dot_tempconv__pb2.TempResponse.FromString,
                _registered_method=True)


class TempConvServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CelsiusToFahrenheit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FahrenheitToCelsius(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TempConvServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CelsiusToFahrenheit': grpc.unary_unary_rpc_method_handler(
                    servicer.CelsiusToFahrenheit,
                    request_deserializer=protos_dot_tempconv__pb2.TempRequest.FromString,
                    response_serializer=protos_dot_tempconv__pb2.TempResponse.SerializeToString,
            ),
            'FahrenheitToCelsius': grpc.unary_unary_rpc_method_handler(
                    servicer.FahrenheitToCelsius,
                    request_deserializer=protos_dot_tempconv__pb2.TempRequest.FromString,
                    response_serializer=protos_dot_tempconv__pb2.TempResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tempconv.TempConvService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tempconv.TempConvService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TempConvService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CelsiusToFahrenheit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempconv.TempConvService/CelsiusToFahrenheit',
            protos_dot_tempconv__pb2.TempRequest.SerializeToString,
            protos_dot_tempconv__pb2.TempResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FahrenheitToCelsius(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempconv.TempConvService/FahrenheitToCelsius',
            protos_dot_tempconv__pb2.TempRequest.SerializeToString,
            protos_dot_tempconv__pb2.TempResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
